### Server

### Login user
POST http://localhost:5000/user/login
Authorization: Bearer am9jZWxpbm9fMTY2NTE4MDczNDpzZW5oYTEyMw==


### List all users
GET http://localhost:5000/users



### Create a new user
POST http://localhost:5000/user
Content-Type: application/json

{
    "name": "Jocelino",
    "username": "jocelino_{{$timestamp}}",
    "email": "jocelino_{{$timestamp}}@email.com",
    "password": "senha123"
}


#####################################################################
################### HUNCHES
#####################################################################

POST http://localhost:5000/hunch
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbDh6MW02dTkwMDAwZ2kwY2NjeWIyeWg5IiwibmFtZSI6ImpvY2VsaW5vXzE2NjUxODA3MzQiLCJpYXQiOjE2NjUxODQ4NDB9.1Mfh_LEnVInGZ0UsAAFJvX9UmmUiebB1ZSCh3YbtN-o
Content-Type: application/json

{
    "homeTeamScore": 1,
    "awayTeamScore": 1,
    "gameId": "cl8vy8t3l0000gi1g2ee2lje1"
}
